### ISSUE TITLE
Duplicates core package

### ISSUE THREAD

**Issue by rchl** [phts/JSTemplateStringEnhancements#4]
Latest dev builds of Sublime have already introduced handling for $ in template literals. I wouldn't want to use third party package for such core functionality.
- Do you think your implementation is an improvement over default implementation? If so, maybe you could upstream your changes.
- If you insisting on providing that functionality for older versions, maybe there is a way to have it enabled conditionally, only for versions that don't support it already?
- The only useful function for me is to convert string to template string so that's the reason for questions above.

**Comment by phts** [comment]
You are right. ST already includes this functionality so I will remove it from the package and leave only converting string to single/double quotes.
